Display end-of-run graph time strings on y-axis
momentum-mod/panorama pull request #115
Opened 2024-01-19 23:05 UTC by benjl

Closes momentum-mod/game/issues/1995

Made the time axis of the end of run graph use formatting based on the extents of the graph, using just seconds, `m:ss`, or `h:mm` where appropriate, and increased spacing slightly so that longer labels like `+mm:ss` don't shrink down.  
(Also, I used `$.Localize()` to check what stat is being compared and I'm not entirely sure if it's bad to do or not)
### Checks

-   [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
-   [x] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
-   [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
-   [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review
-   [x] All changes requested in review have been `fixup`ed into my original commits.
-   [x] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding-terms) below

2024-01-19 23:27 UTC, benjl commented
![image](https://github.com/momentum-mod/panorama/assets/32750171/fceb3b2a-8a3c-44b1-94e1-40ad4dcd6050)
![image](https://github.com/momentum-mod/panorama/assets/32750171/03899199-e0b1-40e3-a96f-851a2a421abb)
![image](https://github.com/momentum-mod/panorama/assets/32750171/d15337ca-2199-4ecb-9f4b-f5949e51b7f9)
![image](https://github.com/momentum-mod/panorama/assets/32750171/bb43571a-ee1a-41b4-a261-f0c5147282ea)
![image](https://github.com/momentum-mod/panorama/assets/32750171/14eca118-cc68-41a8-af0a-b7f45a674b4f)

2024-01-19 23:52 UTC, tsa96 requested changes

2024-01-19 23:52 UTC, tsa96 commented on scripts/components/graphs/line-graph.js
> +					if (markerValue === 0) sign = '';
I actually really think a nested ternary is more readable here. `const sign = markerValue > 0 ? '+' : markerValue < 0 ? '-' : '';`

2024-01-20 00:30 UTC, tsa96 approved these changes
Looks great! Thanks for this :)

2024-01-20 00:40 UTC, tsa96 requested changes

2024-01-20 01:35 UTC, tsa96 approved these changes

2024-01-20 02:10 UTC, merged