Timer splits for stages and ordered/required checkpoints
momentum-mod/panorama pull request #160
Opened 2024-11-26 19:11 UTC by Panzerhandschuh

I will come back to this and add support for unordered/optional checkpoints.

### Checks

-   [ ] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
-   [ ] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
-   [ ] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
-   [ ] My branch is functionally complete; the only changes to be done will be those potentially requested in code review
-   [ ] All changes requested in review have been `fixup`ed into my original commits.
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding-terms) below

### POEditor JSON Strings (if needed)

```json
[
	{
		"term": "",
		"definition": ""
	}
]
```

2024-11-27 17:30 UTC, PeenScreeker approved these changes

2024-11-27 17:30 UTC, PeenScreeker commented
lgtm

2024-11-28 21:01 UTC, tsa96 requested changes

2024-11-28 21:12 UTC, tsa96 commented
This might not fit into current code perfect but for `RunStatsComparison` you could do something like this: 
```ts
const RunStatsUnits: Record<string, string> = {
	maxOverallSpeed: 'ups',
	maxHorizontalSpeed: 'ups',

	overallDistanceTravelled: 'units',
	horizontalDistanceTravelled: 'units',

	jumps: 'jumps',
	strafes: 'strafes'
};

export interface RunStatsComparison {
	name: string;
	unit: string;
	baseValue: number;
	comparisonValue: number;
	diff: number;
}

export function GenerateStatsComparison(baseStats: RunStats, comparisonStat: RunStats): RunStatsComparison[] {
	return (Object.keys(baseStats) as Array<keyof RunStats>).map((key) => ({
		name: key,
		unit: RunStatsUnits[key],
		baseValue: baseStats[key],
		comparisonValue: comparisonStat[key],
		diff: baseStats[key] - comparisonStat[key]
	}));
}
```

2024-11-30 17:17 UTC, tsa96 approved these changes
Was trying to understand what was going on in the constructor of the Comparison class and realised it's never even getting used.

We shouldn't need to keep Run_OLD around given the new RunSplits stuff, and so I don't really see the point of this class. The only thing that's still obviously relevant are generateSplits (though never gets used atm) and generateSubsegmentSplit. These are static methods and don't really have anything to do with comparisons, so they should just be plain functions.

We could pull this all out of classes and use constructors, but that's absolutely not a requirement in JS/TS, and since we have several instances of constructor-like functions that return arrays of what they should be constructing, it seems easier to skip using classes and just use interfaces + pure functions. We can then name the import of common/timer.ts in some places to scope the functions better.

Sorry to piggy-back your work but I *really* want to get the data structures organised well here and avoid using any of these unnecessary old classes. I've just spent a half hour reorganising stuff a little doing the WIP refactoring of the endofrun code. Let's merge what you have here, then I'm gonna push my WIP stuff on top of that, and I'd appreciate it if you or anyone else worked off of there when doing end of run

2024-11-30 17:23 UTC, merged