Add HUD hint text
momentum-mod/panorama pull request #29
Opened 2022-07-14 11:02 UTC by SlidyBat

Allows env_hudhint to work again. Closes https://github.com/momentum-mod/game/issues/1376.

2022-07-14 11:15 UTC, tsa96 requested changes
We shouldn't use Valve stuff like this, I'd much rather we have as little styling as possible, rather than just copying stuff over.

2022-07-14 11:21 UTC, tsa96 approved these changes
Much better, thanks! I'll be doing a big load of styling stuff soon doing the new colour space stuff plus HUD improvements, should be able to work on styling then.

2022-07-29 06:48 UTC, Gocnak approved these changes

2022-07-29 06:49 UTC, Gocnak commented
Needs styling touched up with Prettier.

2022-08-27 19:33 UTC, Gocnak approved these changes

2022-08-27 19:34 UTC, merged