Ammo hud panel and styling
momentum-mod/panorama pull request #43
Opened 2022-11-20 03:09 UTC by chovelyoukai

This PR adds a simple counter hud for the player's current ammunition.

2022-11-20 23:55 UTC, tsa96 requested changes

2022-11-20 23:55 UTC, tsa96 commented on styles/hud/ammo.scss
> +}
Missing newline?

2022-11-30 08:11 UTC, tsa96 commented
Not sure what the "Waiting for status to be reported" is doing holding up CI but def need to resolve that conflict

2022-12-06 02:56 UTC, Gocnak commented
> Not sure what the "Waiting for status to be reported" is doing holding up CI but def need to resolve that conflict

Likely needs rebasing, it's not able to be merged so Actions probably doesn't want to run.

2022-12-17 20:04 UTC, Gocnak approved these changes

2022-12-17 20:04 UTC, merged