Feat/enhanced snap highlight
momentum-mod/panorama pull request #68
Opened 2023-02-10 06:51 UTC by PeenScreeker

This pull request enhances the functionality of snap hud for defrag. This pull request also lays the groundwork for the CGAZ 2.0 overhaul.

Changes:
- When using highlight mode 2, only the portion of the highlighted snap zone that can provide acceleration is colored
- Zones (snaps, CGAZ, mirror) are refactored as objects containing a reference to some panel, angles representing the left and right edges of that panel, and pixel values for the left and right edge of the panel on screen.
- Cleaned up member variable names to align with style convention (camelCase)
- Fix js error when scaling/interpolating across a range with 0 distance.

### Checks

-   [ ] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
-   [ ] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
-   [ ] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
-   [ ] My branch is functionally complete; the only changes to be done will be those potentially requested in code review
-   [ ] All changes requested in review have been `fixup`ed into my original commits.
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding-terms) below

```

2023-02-10 09:00 UTC, tsa96 requested changes

2023-02-10 14:10 UTC, PeenScreeker commented on scripts/hud/cgaz.js
> +
yep, good shout. This makes more sense, and is really the outcome I wanted.

2023-02-10 14:11 UTC, PeenScreeker commented on scripts/hud/cgaz.js
> +		new ZoneObject($('#MirrorSplitZone'))
I think I'm going to end up changing this to create the panels dynamically when the angles are calculated from `snapAccel` (based on the approach used in the multi-pitch PR). Once that commit is added, I'll notify you

2023-02-10 16:20 UTC, PeenScreeker commented on scripts/hud/cgaz.js
> +		new ZoneObject($('#SnapZone11'))
I think I will change to something like this soon. Imo, these could be created dynamically like the multi-pitch PR does with pitch lines inside their container.

This refactor is kind off a PITA though, and I would rather create an issue to be tackled in the next incremental CGAZ 2,0 change.

2023-02-10 18:43 UTC, PeenScreeker commented on scripts/hud/cgaz.js
> +		new ZoneObject($('#MirrorSplitZone'))
I've made this change locally, but ESLint yells at me, can't commit.

2023-02-11 01:16 UTC, tsa96 commented on scripts/hud/cgaz.js
> +		new ZoneObject($('#MirrorSplitZone'))
What's it complaining about? Can't think what would be a problem with this

2023-02-11 01:18 UTC, tsa96 commented on scripts/hud/cgaz.js
> +		new ZoneObject($('#SnapZone11'))
What's the issue with this refactor? Shouldn't it only be affecting these lines, and instantiate the exact same array?

Still, if you'd rather do it after the refactor that's reasonable. I'll mark this and above as resolved.

2023-02-11 02:02 UTC, PeenScreeker commented on scripts/hud/cgaz.js
> +		new ZoneObject($('#MirrorSplitZone'))
"Move arrow function to outer scope"

2023-02-11 02:06 UTC, PeenScreeker commented on scripts/hud/cgaz.js
> +		new ZoneObject($('#SnapZone11'))
I would like to generate these when calculating all possible angle breakpoints. It's currently doing that every frame, but I'd like to move that to only happen when haste state changes.

Between the camel case renaming and moving code around in the main snap block, it got pretty nasty keeping everything separated commit-by-commit. I think I can bang it out while I'm travelling.

2023-02-12 17:14 UTC, tsa96 commented
Weird commit message in #[681c33c](https://github.com/momentum-mod/panorama/pull/68/commits/681c33cded61b53859717082aeef2035428d46ae) @PeenScreeker

2023-02-13 02:18 UTC, PeenScreeker commented
> Weird commit message in #[681c33c](https://github.com/momentum-mod/panorama/pull/68/commits/681c33cded61b53859717082aeef2035428d46ae) @PeenScreeker

ssh didn't want to comply, but I finally got this fixed.

2023-02-14 07:17 UTC, tsa96 approved these changes
Sorry!! Thought this was already approved

2023-02-14 07:19 UTC, Gocnak approved these changes

2023-02-14 07:19 UTC, merged